apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "auralbooks.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: auralbooks
  template:
    metadata:
      labels:
        app: auralbooks
    spec:
      serviceAccountName: auralbooks-sa
      containers:
        - name: app
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 8080
          resources:
            {{- toYaml .Values.resources | nindent 12 }}