apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: auralbooks-policy
spec:
  podSelector:
    matchLabels:
      app: auralbooks
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector: {}