trigger:
  branches:
    include:
      - main

variables:
  tag: preprod

stages:
  - stage: Deploy
    jobs:
      - job: Deploy
        steps:
          - template: templates/steps-helm-deploy.yml
            parameters:
              environment: preprod