trigger: none

stages:
  - stage: Approval
    jobs:
      - job: WaitForApproval
        pool: server
        steps:
          - task: ManualValidation@0
            inputs:
              instructions: 'Approve production deployment'
              timeoutInMinutes: 1440

  - stage: Deploy
    dependsOn: Approval
    jobs:
      - job: Deploy
        steps:
          - template: templates/steps-helm-deploy.yml
            parameters:
              environment: prod